name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Adjust to your main branch name if different
  pull_request:
    branches:
      - main  # Trigger the workflow on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (this is recommended for cross-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (you can replace with other Docker registries like GitHub Packages or AWS ECR)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "alekseiy"  # Set Docker Hub username as secret in GitHub
          password: "Avomatkalashnikov"  # Set Docker Hub password as secret in GitHub

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t alekseiy/lunaris .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push alekseiy/lunaris:latest

